### ISSUE TITLE
Estudar e aplicar os testes unitários

### ISSUE THREAD

**Issue by G16C** [fga-eps-mds/2022-2-IsItKbs#100]
## Descrição
Nessa issue iremos estudar e aplicar os testes unitários para o nosso sistema

## Tarefas
- [x] Estudar o funcionamento dos testes unitários 
- [x] Pesquisar qual ferramenta de testes unitários é mais utilizada para o nosso framework
- [x] Configurar ambiente com a ferramenta de testes e documentar como é feita essa configuração
- [x] Criar testes unitários
- [x] Verificar  a porcentagem de cobertura dos testes com o codecov/coveralls e documentar a configuração e resultado do codecov

## Critério de aceitação
- [x] Pelo menos 3 testes devem ser criados
- [x] A cobertura do codecov deve ser de pelo menos 90%
- [x] A configuração do ambiente deve estar funcionando

**Comment by PauloVictorFS** [comment]
encontrei esses sites que possuem informações relevantes sobre testes 

https://medium.com/pykes-technical-notes/testing-machine-learning-systems-unit-tests-38696264ee04
https://madewithml.com/courses/mlops/testing/
https://research.google/pubs/pub46555/

**Comment by G16C** [comment]
Os testes já foram aplicados.

**Comment by G16C** [comment]
Os testes já foram aplicados.

**Comment by G16C** [comment]
Os testes foram aplicados.
