### ISSUE TITLE
criação do Naive Bayes

### ISSUE THREAD

**Issue by PauloVictorFS** [fga-eps-mds/2022-2-IsItKbs#101]
## Descrição
É necessário a análise e a criação do melhor algoritmo Naive Bayes  que se encaixe no  projeto

## Tarefas

- [x] Criação do Naive Bayes

## Critério de aceitação

- [x] Naive Bayes criado

**Comment by arthurgrandao** [comment]
Após os companheiros atualizarem suas funções (e leves complicações 😅), a minha parte está finalizada e integrada ao resto do projeto.
