### ISSUE TITLE
Função de análise de frequência dos caracteres em keyboad smashing

### ISSUE THREAD

**Issue by arthurgrandao** [fga-eps-mds/2022-2-IsItKbs#102]
## Descrição
Iniciar o protótipo de uma função que exiba ao usuário a frequência de determinados caracteres em um keyboard smashing, seja uma frequência simples ou um heatmap do teclado. Com o intuito de ajudar o usuário a visualizar e analisar os dados.

## Tarefas

- [x] Decidir os métodos a serem utilizados;
- [x] Criar a função para análise;

## Critério de aceitação

- [x] Deixar os retornos da função de acordo com o proposto;

**Comment by G16C** [comment]
@nando3d3, mano tem alguma ideia de método para ser usado? Eu pensei em usar uma daquelas bibliotecas que tinha falei, o seaborn, para plotar o gráfico da frequência. Vou deixar aqui a biblioteca.

https://seaborn.pydata.org/tutorial/introduction.html

**Comment by nando3d3** [comment]
Realizei algumas mudanças nas funções em geral e também adicionei a função de frequência de kbs. Pode ser vista em [ks_object.ipynb](https://github.com/fga-eps-mds/2022-2-IsItKbs/blob/features_sidney/notebooks/ks_object.ipynb)
