### ISSUE TITLE
Criação de uma Função que substitua KeyBoardSmashing Indentificados pelo usuário.

### ISSUE THREAD

**Issue by RafaelCLG0** [fga-eps-mds/2022-2-IsItKbs#103]
## Descrição
Criar uma função que dado um arquivo.csv ou DataFrame do Pandas fornecido pelo usuário substitua os KeyBoardSmashings indentificados.

## Tarefas

- [x] Ler o arquivo.csv ou DataFrame do Pandas fornecido pelo usuário.
- [x] Fazer a limpeza do dados escolhidos pelo usuário.
- [x] Retornar os KeyBoardSmashings identificados e alterados.

## Critério de aceitação

- [x] Apresentar uma função coerentes com os critérios e funcional.

**Comment by dougAlvs** [comment]
Fiz a criação de um protótipo da função, segue o link do  commit b283dba0a9dba1d6c02e0bb109c29a92391a6ee3 .

**Comment by RafaelCLG0** [comment]
Protótipo criado e aprovado para ser executado na próxima issue.
