### ISSUE TITLE
Tradução da Gitpage

### ISSUE THREAD

**Issue by G16C** [fga-eps-mds/2022-2-IsItKbs#104]
## Descrição
Essa issue será direcionada para a tradução da nossa documentação para o inglês, tendo em vista a necessidade de tal para a autorização do uso do Zenhub

## Tarefas
- [x] Traduzir a documentação

## Critério de aceitação
- [x] Os textos devem ser traduzidos em acordo com a norma gramatical do inglês

**Comment by PauloVictorFS** [comment]
realizei a tradução do readme , da contributing.md , e de outros arquivos relacionados ao github comunity standards, e enviei para o zenhub observar

**Comment by PauloVictorFS** [comment]
Pull request realizado  e aceito
