### ISSUE TITLE
Preparar roteiro de testes

### ISSUE THREAD

**Issue by nando3d3** [fga-eps-mds/2022-2-IsItKbs#111]
## Descrição
Para a realização dos testes unitários por todo o grupo é necessário elencar as etapas para a sua realização.

## Tarefas

- [x] Criar testes para as funções feitas na release 1
- [x] Configurar o ambiente para aplicação de testes

## Critério de aceitação

- [x] Os testes devem ser apresentes de maneira satisfatória

**Comment by dougAlvs** [comment]
FIz a atualização dos testes para a função is_kbs com mais alguns casos.

**Comment by arthurgrandao** [comment]
Eu também 🙋🏻
