### ISSUE TITLE
Integrar novas funções 

### ISSUE THREAD

**Issue by arthurmlv** [fga-eps-mds/2022-2-IsItKbs#112]
## Descrição
Integrar funções de frequência e substituição de keyboard smashing.

## Tarefas

- [x] Função de frequência;
- [x] Função de substituição.
## Critério de aceitação

- [x] Implementação de ambas e funcionando apropriadamente.

**Comment by nando3d3** [comment]
@RafaelCLG0 @dougAlvs implementei as novas funções nesse [notebook](https://github.com/fga-eps-mds/2022-2-IsItKbs/blob/novas_funcoes/notebooks/ks_object.ipynb). Gostaria que revisassem e comentassem novas mudanças, caso sejam feitas
