### ISSUE TITLE
Expansão da base de dados do pacote

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#114]
## Descrição

Tendo em vista que o nosso modelo apresenta falhas na detecção de diversas palavras comuns, é necessário que o alimentemos com mais dados para melhorar a acurácia.
## Tarefas

- [x] Adicionar mais dados tanto de linguagem natural como keyboard smashings.
- [x] Repetir o treinamento do(s) modelo(s) com os novos dados
- [x] Avaliar os resultados obtidos

## Critério de aceitação

- [x] É preciso que a acurácia geral aumente, sendo assim, o algoritmo não pode passar a identificar errado palavras que ele identificava corretamente antes da adição dos dados.

**Comment by arthurgrandao** [comment]
Eu encontrei uma base que pode ajudá-los: [https://github.com/dwyl/english-words](https://github.com/dwyl/english-words)

**Comment by RafaelCLG0** [comment]
Realizei alguns testes na base de dados atualizada pelo @arthurmlv. Encontrei um problema na hora de executar o código, mas era só uma celula trocada que corrigi depois.
