### ISSUE TITLE
Implementar formas mais eficientes do algoritmo identificar keyboard smashings

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#122]
## Descrição

Após adicionarmos mais dados no treinamento dos nossos algoritmos, percebemos que a acurácia não está aumentando significativamente. Sendo assim, é necessário que encontremos outras maneiras mais eficientes de identificar keyboard smashings para melhorar a acurácia do algoritmo.
## Tarefas

- [ ] Encontrar novos critérios para o algoritmo identificar keyboard smashings.

## Critério de aceitação

- [ ] O algoritmo deve ser testado e avaliado com as novas features.

**Comment by dougAlvs** [comment]
Um critério interessante que encontrei foi o TTR, segue um breve resumo:
Type-token ratio (TTR) is a measure of lexical diversity in text. It is calculated by dividing the number of unique words (types) by the total number of words (tokens) in a text. TTR is a simple yet effective measure of lexical diversity, which can be used to compare the lexical richness of different texts or authors, or to detect changes in lexical diversity over time.

A text with a high TTR value is considered to be more lexically diverse, as it contains a larger number of unique words in relation to the total number of words. On the other hand, a text with a low TTR value is considered to be less lexically diverse, as it contains a smaller number of unique words in relation to the total number of words.

In the context of keyboard smashing detection, TTR can be used as a feature to detect random text as it will have a low TTR value. Since keyboard smashing text is usually not coherent or meaningful, it will have a high number of repeated words and characters, and therefore a low TTR value.

**Comment by dougAlvs** [comment]
Especificamente para o random forest, adicionei um modelo que seleciona os 30k ngramas que ele acredita serem mais importantes na determinação do keyboard smashing dentre os em torno de 150k da nossa base. Com isso, a acurácia do modelo random forest aumentou muito, mas é preciso fazer uns testes para ter certeza de como ele se sai nas mais diversas situações. As alterações já estão na ks.py na branch "melhora_acuracia".

**Comment by arthurgrandao** [comment]
Após as análise e estudos acerca do assunto, conseguimos aumentar a acurácia.
