### ISSUE TITLE
configurar o zenhub do grupo

### ISSUE THREAD

**Issue by PauloVictorFS** [fga-eps-mds/2022-2-IsItKbs#15]
## Descrição
Para organizar melhor o trabalho , é necessário a criação de um zenhub para colocar sprints backlogs e organizar de forma geral nossas sprints

## Tarefas
- [x] criar o zenhub que servirá de padrão para o grupo

## Critério de aceitação
- [x] zenhub criado

**Comment by dougAlvs** [comment]
FIz a adição de alguns épicos e o sprint backlog para a sprint seguinte, juntamente com as respectivas issues a serem fechadas. Para verificação entrar no zenhub.
