### ISSUE TITLE
Visualizar trabalhos de grupos anteriores

### ISSUE THREAD

**Issue by RafaelCLG0** [fga-eps-mds/2022-2-IsItKbs#2]
## Descrição
Visualizar trabalhos de grupos anteriores para entender inicialmente como é estruturado o projeto e usar como referência.

## Tarefas
- [x] Visitar repositórios de projetos realizados nos semestres anteriores.

## Critérios de Aceitação
- [x] Toda a equipe deve visitar e estudar sobre a estrutura dos projetos anteriores.

**Comment by RafaelCLG0** [comment]
Revisei o projeto do Cebraspe Tracker sobre a organização da sua gh-pages (https://github.com/fga-eps-mds/Cebraspe-Tracker).

**Comment by G16C** [comment]
Dentre os diversos documentos post morten disponibilizados pela professora, um dos que mais me chamou atenção, pela criatividade e pelo feedback foi o do projeto (https://github.com/fga-eps-mds/2022-1-PokeRanking)

**Comment by dougAlvs** [comment]
Revisei o projeto Anunbis (https://github.com/fga-eps-mds/2020.2-Anunbis) para buscar aprender com os erros que o grupo deles fizeram.

**Comment by arthurgrandao** [comment]
Dei uma olhada em alguns repositórios da disciplina, vendo como os outros grupos se organizaram para o desenvolvimento do projeto. Gostei de alguns projetos, entre eles eu destaco o [Aix](https://github.com/fga-eps-mds/2019.1-Aix).
