### ISSUE TITLE
Criar a estrutura de pastas do projeto

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#20]
## Descrição
Criação de uma estrutura de pastas organizada e condizente com os padrões de projetos de Machine Learning, de forma a facilitar a execução e reprodutibilidade desse.

## Tarefas
- [x] Verificar os padrões da comunidade para projetos de ML.
- [x] Implantar o padrão mais adequado

## Critérios de Aceitação
- [x] Toda a organização de dados, scripts e modelos deve estar implantada

**Comment by G16C** [comment]
Como essa issue já foi concluída irei fechá-la.

**Comment by G16C** [comment]
Como essa issue já foi concluída irei fechá-la.
