### ISSUE TITLE
Adicionar as duas bases de dados a serem usadas

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#21]
## Descrição
Adição das duas bases de dados escolhidas na pasta designada aos dados brutos, de forma que seu acesso para processamento seja facilitado.

## Tarefas
- [x] Adicionar as bases da dados na pasta designada.

## Critérios de Aceitação
- [x] A pasta de dados brutos deve ter os arquivos das duas bases de dados.

**Comment by nando3d3** [comment]
Encontrei esse site que lista alguns open datasets que podem ser interessantes para o nosso projeto:
[20 Open Datasets for Natural Language Processing](https://odsc.medium.com/20-open-datasets-for-natural-language-processing-538fbfaf8e38)
[Best Public Datasets for Machine Learning and Data Science](https://pub.towardsai.net/best-datasets-for-machine-learning-data-science-computer-vision-nlp-ai-c9541058cf4f)

Além disso, acho interessante procurar datasets sobre nicknames (apelidos e nomes em jogos, por exemplo)

**Comment by dougAlvs** [comment]
Fiz a adição de uma das base de dados, a 20 News Dataset

**Comment by G16C** [comment]
Vou fazer a limpeza da base de dados blogcorpus. Assim que terminar avisarei aqui para que vocês já possam verificá-la.

**Comment by dougAlvs** [comment]
Link do dataset do blogger
https://www.kaggle.com/datasets/rtatman/blog-authorship-corpus

**Comment by PauloVictorFS** [comment]
junto com o gabriel , limpamos as duplicatas e as linhas vazias através do pair programming. após isso , retirei as palavras que não estavam em ingles  e os dígitos numéricos. porém , encontramos uma base de dados melhor e mais completa, afinal a nossa estava tendo problemas, e decidimos mudar para a base de dados Reuters
