### ISSUE TITLE
Processar cada uma das bases de dados para um nível intermediário

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#22]
## Descrição
Pegar os dados brutos e refina-los de maneira que os scripts de feature extraction possam trabalha-los para identificar as features e deixa-los prontos para o aprendizado dos algoritmos

## Tarefas
- [x] Fazer o processamento necessário na base de dados 1
- [x] Fazer o processamento necessário na base de dados 2
- [x] Armazenar os dados processados na pasta de dados intermediária

## Critérios de Aceitação
- [x] Os dados pré-processados da base de dados 1 deve estar na pasta de dados intermediária
- [x] Os dados pré-processados da base de dados 2 deve estar na pasta de dados intermediária

**Comment by dougAlvs** [comment]
Exemplos de processamento da base de dados do 20 news groups:
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html#examples-using-sklearn-datasets-fetch-20newsgroups

**Comment by PauloVictorFS** [comment]
base de dados reuters em nível intermediário e pronta para ser manipulada

**Comment by G16C** [comment]
Como as duas bases de dados estão limpas irei fechar essa issue.
