### ISSUE TITLE
Criar scripts para feature extraction 

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#23]
## Descrição
Criação de scripts funcionais que consigam pegar as bases de dados intermediárias e realizar a feature extraction delas, deixando-as prontas para alimentar os algoritmos de Machine Learning e as armazenando na pasta de dados processados.

## Tarefas
- [x] Criar e testar os scripts de feature extraction.

## Critérios de Aceitação
- [x] Os scripts devem estar funcionando e capazes de trabalhar em ambas as bases de dados.

**Comment by arthurmlv** [comment]
Dois problemas encontrados:
1 - A função do scikit learn para a vetorização em Tfidf incapacita a utilização das stopwords se a análise for por char, tal função só funciona se for por palavras. Portanto, caso seja necessário, há de se pensar em outra forma para utilizar as stopwords.
2 - Verificar se há a necessidade de fazer o processo de stemming, que é reduzir palavras maiores na base de dados para palavras-chave, mas, num primeiro momento, para mim, o uso de tal ferramenta poderia afetar a detecção de keyboard mashing.

**Comment by arthurmlv** [comment]
Dado o objetivo do trabalho, inferiu-se que a utilização de stopwords e stemming afetaria, de fato, a detecção de keyboard mashing. Portanto, a implementação de tais mudanças se mostrou desnecessária.

**Comment by dougAlvs** [comment]
Os scripts para feature extraction de ambas as bases de dados estão presentes na pasta adequada e funcionando.
