### ISSUE TITLE
Definir product owner (PO) do projeto

### ISSUE THREAD

**Issue by nando3d3** [fga-eps-mds/2022-2-IsItKbs#25]
O **product owner** é geralmente o principal interessado de um projeto - geralmente alguém do marketing ou gerenciamento de produto, ou o principal usuário de um sistema. Portanto, o PO faz maxima o desenvolvimento do produto através do gerenciamento dos backlogs do produto, incrementando, corrigindo falhas, revisando e colocando tudo para funcionar conforme a expectativa do cliente e, sobretudo, do usuário final.
Na conclusão de cada **sprint**, o(a) PO e a equipe de desenvolvimento apresentam o produto ao cliente, recebendo o feedback e anotando os incrementos que são eventualmente pedidos.

## Descrição
O **product owner** é geralmente o principal interessado de um projeto - geralmente alguém do marketing ou gerenciamento de produto, ou o principal usuário de um sistema. Portanto, o PO faz maxima o desenvolvimento do produto através do gerenciamento dos backlogs do produto, incrementando, corrigindo falhas, revisando e colocando tudo para funcionar conforme a expectativa do cliente e, sobretudo, do usuário final.
Na conclusão de cada **sprint**, o(a) PO e a equipe de desenvolvimento apresentam o produto ao cliente, recebendo o feedback e anotando os incrementos que são eventualmente pedidos.

## Tarefas

- [ ] Escolher Product Owner

## Critério de aceitação

- [ ] Pareamento sobre a escolha com todos do grupo

**Comment by PauloVictorFS** [comment]
pelo brasil , meu voto é douglas

**Comment by dougAlvs** [comment]
Após uma reunião, ficou definido que eu seria o PO.
