### ISSUE TITLE
Miro

### ISSUE THREAD

**Issue by PauloVictorFS** [fga-eps-mds/2022-2-IsItKbs#27]
### Descrição
Iniciar a criação da parte visual das histórias de usuários com o miro.
### Tarefas

- [x] Abrir uma equipe no miro onde todos possam mais para frente acessar

### Critério de aceitação 

- [x] Os responsáveis devem liberar a equipe para todos

**Comment by dougAlvs** [comment]
Segue o link da primeira versão do user story map no miro:
https://miro.com/app/board/uXjVPAq2MHY=/

**Comment by G16C** [comment]
Lá nas histórias de usuários poderia ser acrescentado quem é o PO e quem é o SCRUM MASTER?

**Comment by dougAlvs** [comment]
https://miro.com/welcomeonboard/V2tnS2E1Zjd2Q3lzREhoY3ZJRmN2QVQxQkdKeXNnelhYQ2N1WDNaejRvQ1FMaklXYURYbHI1d05Vd0JXYUdzYXwzNDU4NzY0NTM4NDg2OTQ1NTczfDI=?share_link_id=352474241903
Link com convite para o time do miro, pra quem ainda não tem acesso.

**Comment by dougAlvs** [comment]
O team do miro já está criado e já tem uma versão inicial do user story map presente no site.
