### ISSUE TITLE
Iniciar a criação da git page

### ISSUE THREAD

**Issue by PauloVictorFS** [fga-eps-mds/2022-2-IsItKbs#29]
## Descrição
Para organizar melhor o trabalho , é necessário a criação de uma git page , que apresente informações relevantes do projeto

## Tarefas
- [x] Elaborar uma git page condizente com nosso trabalho

## Critério de aceitação
- [x] git page criada

**Comment by dougAlvs** [comment]
Fiz o commit de um diagrama de pacotes em uma branch separada para adicionarmos na gitpage depois.
Link: https://github.com/fga-eps-mds/2022-2-Squad03/blob/adicao_documentacao/docs/images/diagramaPacotes.png
