### ISSUE TITLE
Criação de Planilha Horas Trabalhadas

### ISSUE THREAD

**Issue by PauloVictorFS** [fga-eps-mds/2022-2-IsItKbs#3]
**Descrição**
Esta issue foi feita pela necessidade criar um documento para controle de horas trabalhadas

**Tarefas**

- [x] Criar a planilha e checar se foi realizada corretamente

**Critério de aceitação
- [x] Planilha pronta conforme o gosto do grupo

**Comment by PauloVictorFS** [comment]
Aqui está a planilha criada, por favor checar para ver se está tudo correto , e fechar a issue
https://1drv.ms/x/s!AoY1rhP4lwt4iLofHuXaAvjFfvJehQ?e=V81Vvo

**Comment by dougAlvs** [comment]
Eu zerei o horário dos dias que não foram trabalhados pra já começar a contabilizar o horário corretamente e adicionei uma coluna de descrição pra por um resumo do que fez no dia.
