### ISSUE TITLE
Estudar python e machine learning

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#4]
## Descrição
Buscar materiais sobre como escrever código e lidar com dados na linguagem python, além de entender o básico do que é machine learning e como ela funciona.

## Tarefas
- [x] Estudar o básico de python
- [x] Estudar o básico de pandas
- [x] Estudar o básico de machine learning
 
## Critérios de aceitação
- [x] Todos os membros devem ter uma noção dos assuntos

**Comment by G16C** [comment]
https://www.hashtagtreinamentos.com/introducao-pandas-python?gclid=Cj0KCQiA37KbBhDgARIsAIzce15ANj1jWaMDamEjRyuX4eU3mz_RxBN0BhDpHYaKhZjH2wDQw-v50kwaAlpTEALw_wcB

Segue uma aula sobre o básico da biblioteca pandas do python

**Comment by G16C** [comment]
https://code.visualstudio.com/docs/datascience/data-science-tutorial

Segue um outro exemplo de implementação de machine learning em python
