### ISSUE TITLE
Criação do código de conduta

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#44]
## Descrição
Elaboração de um código de conduta de acordo com os padrões da comunidade de software livre

## Tarefas
- [x] Adicionar o código de conduta no repositório.

## Critérios de Aceitação
- [x] O código de conduta estar de acordo com os padrões e adicionado no repositório.

**Comment by G16C** [comment]
Já enviei o pull request do código de conduta. Depois disso acho que podemos dar um merge com a community_std.

**Comment by G16C** [comment]
Como já demos o merge irei fechar essa issue
