### ISSUE TITLE
Revisar e excluir branchs inutilizadas

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#46]
## Descrição
Olhar as branchs presentes atualmente no projeto e excluir as que não estão sendo mais utilizadas.

## Tarefas
- [ ] Revisar as branchs.
- [ ] Excluir as inutilizadas.

## Critérios de Aceitação
- [ ] Branchs desnecessárias excluídas.

**Comment by G16C** [comment]
Por qual vocês acham melhor começar a remoção?

**Comment by dougAlvs** [comment]
Foi feita a remoção das branchs inutilizadas que já haviam sofrido merge.
