### ISSUE TITLE
Formatar os pull requests anteriores de acordo com o template elaborado

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#48]
## Descrição
Verificar os pull requests antigos e, caso necessário, atualiza-los com o template estabelecido.

## Tarefas
- [x] Cada integrante deve verificar seus pull requests antigos e atualiza-los de acordo com o template.

## Critérios de Aceitação
- [x] Todos os pull requests devem seguir o padrão do template escolhido para o projeto.

**Comment by dougAlvs** [comment]
FIz a formatação das minhas issues e pull requests antigas que estavam fora dos padrões.

**Comment by arthurgrandao** [comment]
Formatei o pull request que fiz anteriormente.

**Comment by PauloVictorFS** [comment]
Formatei os meus pull requests de acordo com o padrão
