### ISSUE TITLE
Elaboração do Workflow

### ISSUE THREAD

**Issue by G16C** [fga-eps-mds/2022-2-IsItKbs#51]
### Descrição
Elaborar um Workflow seguindo os padrões da comunidade e as dicas da professora. Já existe um Workflow (incompleto) no Miro, no qual vocês podem se basear. É recomendada a leitura prévia dos padrões da comunidade para um Workflow

### Tarefas
- [x] Elaborar um Workflow usando os templates do Miro e seguindo as normas da comunidade. 
- [x] Após análise, acrescentá-lo na gitpage.

### Critérios de aceitação
- [x] Esse Workflow deve estar em acordo com os padrões da comunidade Git.

**Comment by arthurgrandao** [comment]
Tinham umas palavras com erros de digitação no comentário da issue, arrumei.

**Comment by RafaelCLG0** [comment]
WorkFlow foi criado baseado nos conceitos fornecidos por esse site de como criar um WorkFlow de Machine Learning : https://towardsdatascience.com/workflow-of-a-machine-learning-project-ec1dba419b94.
