### ISSUE TITLE
Reelaborar o User Story Map

### ISSUE THREAD

**Issue by nando3d3** [fga-eps-mds/2022-2-IsItKbs#54]
## Descrição
O User Story Map é um exercício visual que ajuda os gerentes de produto e suas equipes de desenvolvimento a definir o trabalho que criará a experiência de usuário mais agradável. Ele é usado para melhorar a compreensão das equipes sobre seus clientes e priorizar o trabalho. Sendo assim, devido ao novo entendimento do grupo sobre a aplicação dessa ideia, ela deve ser reelaborada.

## Tarefas
O User Story Map deve apresentar: 
- [ ] Indentifcar o que queremos resolver
- [ ] Mapear histórias de usuários em atividades
- [ ] Planejar sprints e releases

## Critérios de aceitação
- [ ] Tópicos das tarefas bem apresentados e divididos de acordo com a necessidade do projeto

**Comment by dougAlvs** [comment]
FIz um protótipo do user storymap, já separando o que precisaríamos para o MVP e coisas além para a segunda release:

![image](https://user-images.githubusercontent.com/98109429/204819027-37d39806-7c78-4321-9db7-888e4bc3638a.png)

Link no miro: https://miro.com/app/board/uXjVPAq2MHY=/?share_link_id=531483841270
