### ISSUE TITLE
Desenvolver a visão do grupo com relação ao projeto

### ISSUE THREAD

**Issue by G16C** [fga-eps-mds/2022-2-IsItKbs#6]
### Descrição
Verificar entendimento de todos quanto o que é keyboard smashing, e a metodologia que será usada para a divisão dos trabalhos e como abordaremos o problema em questão

### Tarefas

- [x] Pesquisar o que pode ser considerado um keyboard smashing

- [x] Organizar e definir a metodologia que as duplas irão aplicar

### Requisitos
Todos do grupo devem entender o que é o keyboard smashing, como ele pode ser definido. Além da divisão dos grupos e a metodologia que irão aplicar

**Comment by G16C** [comment]
https://miro.com/app/board/uXjVPEvl9T4=/

Usaremos o miro para estabelecer as prioridades para a organização do nosso projeto vou colocar cada um de vocês no meu squad.

**Comment by G16C** [comment]
https://miro.com/welcomeonboard/MnpHeDhpSThleGxkZ1plUXRjNFhjY1ZSU2tDNXVycnBmUERQNWF4dlN2UjIwWXFBUFVQU0lBUWJLVlNKU0lUeHwzNDU4NzY0NTM4Mjk4NDQ4MzQxfDI=?share_link_id=200252576932

Convite para entrar na squad do miro

**Comment by PauloVictorFS** [comment]
com relação a keyboard smashing , encontrei esse link do git  (https://github.com/academia-edu/dejunk) que é uma library feita em ruby , em que eles definem keyboard smashing com os seguintes parametros:
-contém bigramas de caracteres que provavelmente não aparecerão em texto real, mas que estão próximos em um teclado. -(bigramas são letras adjacentes, como por exemplo na palavra runtime, em que se junta ru un nt ti im me)
-Começa com um sinal de pontuação inesperado
-Tem muitas palavras muito curtas.
-Não possui vogais.
-Tem caracteres que são repetidos um número irracional de vezes.
podem ser alguns dos parametros que podemos utilizar ou nos basear para realização do nosso trabalho

**Comment by arthurmlv** [comment]
Portanto, é importante definir o que é keyboard mashing e o que seria a visão que a máquina deveria ter dele. Para isso, a ideia de bigramas citada pelo Paulo anteriormente mostra-se interessante para lidar com o assunto, dado que as mais comuns formas de keyboard mashing no fim acabam por ser uma sequência de 2-8 caracteres: de apenas duas teclas em uma só mão até 8 teclas com os quatro dedos de duas mãos.
Por exemplo, como eu faço keyboard mashing com 4 dedos em cada mão: "URIOWEAURPOIWEUROIW". Por mais que seja uma sequência não pensada, ela acaba repetindo alguns padrões, ainda que inversos: UR, IW, OI, IO. Sendo assim, com a ideia dos bigramas, pode-se identificar mashing de diversas formas com um só método. No entanto, para uma melhor acurácia, utilizar-se-á outros meios.
O que não consegui pensar é em uma forma de identificar sequências inteligentes feitas intencionalmente pelo usuário, que não seriam possíveis de se fazer em um keyboard mashing. Por exemplo: qeadzcwrsfxv, uma sequencia feita por duas letras alternadas na horizontal e pulando para a linha de baixo, ao chegar na ultima linha, move-se para a coluna da direita. Mas bom, talvez isso não seja um problema caso alguém simplesmente não queira coisas ininteligíveis ou sem significado para ele.

**Comment by nando3d3** [comment]
Gostaria de acrescentar a discussão que, além de entender o que é o keyboard smashing, é importante que o grupo estude também sobre Processamento de Linguagem Natural (NLP). Deixo aqui um link para iniciar a leitura sobre o assunto: https://www.oracle.com/br/artificial-intelligence/what-is-natural-language-processing/

**Comment by arthurgrandao** [comment]
Adicionando ao que o Arthur falou, esses padrões de teclas variam de acordo com cada tipo de teclado, os quais possuem disposições de teclas diferentes. Outra forma de identificar os keyboard smashings seria detectar o uso de caracteres, ou sequência de caracteres, que não são comuns ou não existem na língua portuguesa.

**Comment by RafaelCLG0** [comment]
Complementando a idea do Arthur Gradão, fiz uma pesquisa sobre como poderiamos identificar o idioma no qual o keyboar smashing foi aplicado e encontrei um código utilizando trigrama de caracteres em python (https://code.activestate.com/recipes/326576/). Como uma sugestão para ser implementada em nosso trabalho.

**Comment by PauloVictorFS** [comment]
com relação ao que o arthurgrandao falou , temos q levar em consideração o  q nosso banco de dados utiliza. no caso de nomes de usuário não necessariamente eles seriam palavras da lingua portuguesa, porém, seriam válidos no sentido do banco de dados (no meu caso o meu antigo username srpaulo12)

**Comment by G16C** [comment]
Bom trabalho. Essa issue ficou bem completa. É ótima para guiar o grupo.
