### ISSUE TITLE
Treinamento do Modelo Selecionado

### ISSUE THREAD

**Issue by RafaelCLG0** [fga-eps-mds/2022-2-IsItKbs#61]
## Descrição

Realizar o treinamento do Algoritmo com o Modelo Selecionado da 
Issue https://github.com/fga-eps-mds/2022-2-Squad03/issues/63 .

## Tarefas

- [x]  Treinar o algoritmo com  o Modelo Escolhido ;
- [x]  Deixar o algoritmo treinado e preparado para implementação das funções.

## Critério de aceitação

- [x]  Gerar resultados com o modelo escolhido para ser avaliado.

**Comment by G16C** [comment]
Posso fechar?

**Comment by G16C** [comment]
Como o treinamento já foi realizado, e está atendendo os critérios de aceitação vou fechar essa issue
