### ISSUE TITLE
Escolha de modelo para a entrega da release 1

### ISSUE THREAD

**Issue by PauloVictorFS** [fga-eps-mds/2022-2-IsItKbs#63]
## Descrição
Para o desenvolvimento do trabalho , faz-se necessário definir um modelo de algoritmo  para o protótipo de alta fidelidade,  como por exemplo , árvore de decisão , Naive Bayes, entre outros , para ser entregue na release 1 do trabalho
## Tarefas
- [x] Analisar lados positivos e negativos de cada um dos tipos para chegar na conclusão do melhor modelo

## Critério de aceitação
- [x] Estudar os modelos e decidir com o auxilio do resto do grupo

**Comment by nando3d3** [comment]
Após discussões e análise do grupo, foi decidido que o algoritmo de **árvore de decisão** será utilizado para a apresentação do projeto no release 1, devido a sua versatilidade. Uma árvore de decisão é um algoritmo de aprendizado de máquina supervisionado que é utilizado para classificação e para regressão. Isto é, pode ser usado para prever categorias discretas (sim ou não, por exemplo), o que se encaixa no que queremos para a primeira entrega: detectar se uma palavra é ou não keyboard smashing.
