### ISSUE TITLE
Entender e criar um pacote python

### ISSUE THREAD

**Issue by arthurgrandao** [fga-eps-mds/2022-2-IsItKbs#64]
## Descrição
Assim que o algoritmo estiver pronto para a release, nós precisaremos criar um pacote python para que seja distribuido.
Essa Issue destina- se ao estudo dessa tecnologia para que possamos implementá-la futuramente.

## Tarefas
- [x] Estudar o empacotamento via python.

## Critério de aceitação
- [x] Compreender o conteúdo estudado.
- [x] Apresentar um exemplo prático sobre o assunto.

**Comment by G16C** [comment]
Posso fechar?
