### ISSUE TITLE
Formatar as issues anteriores de acordo com o template elaborado.

### ISSUE THREAD

**Issue by arthurgrandao** [fga-eps-mds/2022-2-IsItKbs#65]
## Descrição
As issues anteriores não seguiam o padrão desejado pela professora, portanto, devemos atualizá-las para que possam enquadrar-se em relação às demais. 

## Tarefas
- [x] Formatar as issues anteriores de acordo com o template elaborado;

## Critério de aceitação
- [x] As issues anteriores devem estar de acordo com o proposto;

**Comment by RafaelCLG0** [comment]
Formatei minhas issues anteriores de acordo com o novo template estabelicido.

**Comment by PauloVictorFS** [comment]
Formatei minhas issues anteriores de acordo com o template encontrado no repositorio

**Comment by G16C** [comment]
Vou fechar pois o pessoal me garantiu que fizeram certo.
