### ISSUE TITLE
Compressão do modelo criado.

### ISSUE THREAD

**Issue by arthurmlv** [fga-eps-mds/2022-2-IsItKbs#71]
## Descrição 
Comprimir o modelo criado.

## Tarefas
- [x] A partir do modelo já feito, criar um código para comprimir e salvar na pasta models.

## Critério de aceitação
- [x] Modelo comprimido corretamente na pasta solicitada.

**Comment by RafaelCLG0** [comment]
Issue concluida corretamente com Pull Request.
