### ISSUE TITLE
Atualização da gitpage

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#76]
## Descrição
Fazer a adição das novas documentações que foram criadas do projeto na gitpage.

## Tarefas
- [x] Adicionar as documentações na gitpage.

## Critério de aceitação
- [x] Gitpage apresentar as documentações novas

**Comment by nando3d3** [comment]
A atualização das últimas documentações: workflow, userstorymap, guia de contribuiçao
