### ISSUE TITLE
Atualizar o road map do zenhub

### ISSUE THREAD

**Issue by G16C** [fga-eps-mds/2022-2-IsItKbs#81]
### Descrição 
Aplicar as datas no road map do zenhub, a professora irá olhar.

### Tarefas

- [x] Colocar as datas do rod map do miro no zenhub

### Critérios de aceitação 
Deve estar de acordo com o road map da git page

**Comment by RafaelCLG0** [comment]
Atualizei a equipe em relação a utilização do RoadMap do Zenhub.

**Comment by dougAlvs** [comment]
Fiz a atualização das datas dos épicos no zenhub.
