### ISSUE TITLE
Organizar as milestones no Github

### ISSUE THREAD

**Issue by arthurgrandao** [fga-eps-mds/2022-2-IsItKbs#84]
## Descrição

As milestones no Zenhub não estão organizadas de forma correta, por isso, devemos consertá-las.

## Tarefas

- [x] Organizar as milestones no Zenhub.
## Critério de aceitação

- [x] A parte de milestones está de acordo com o proposto pela professora.

**Comment by dougAlvs** [comment]
Foi feita a organização das milestones das semanas que estavam faltando no github.
