### ISSUE TITLE
Reajuste da pontuação das issues.

### ISSUE THREAD

**Issue by arthurmlv** [fga-eps-mds/2022-2-IsItKbs#87]
## Descrição

Ao analisarmos os gráficos de burndown, percebemos a necessidade de ponderar apropriadamente as issues a fim de deixar o gráfico com valores mais realistas dada certa issue comprida.

## Tarefas

- [x] Escolher novamente uma pontuação adequada para a issue criada.
## Critério de aceitação

- [x] Todas as issues foram reajustadas e os pontos estão condizentes com a necessidade e complexidade.

**Comment by arthurgrandao** [comment]
Eu revisei as issues e atribuí as devidas pontuações.

**Comment by RafaelCLG0** [comment]
Realizei os reajustes das issues anteriores com as devidas pontuações.

**Comment by dougAlvs** [comment]
Fiz o reajuste das minhas issues antigas.

**Comment by PauloVictorFS** [comment]
realizei os reajustes das issues antigas

**Comment by G16C** [comment]
Os ajustes solicitados já foram feitos.

**Comment by arthurmlv** [comment]
Também já o fiz.

**Comment by nando3d3** [comment]
Feito
