### ISSUE TITLE
Entender sobre o funcionamento de ML e PLN

### ISSUE THREAD

**Issue by nando3d3** [fga-eps-mds/2022-2-IsItKbs#9]
## Descrição
Como um branch de inteligência artificial, o **processamento de linguagem natural (PLN)** usa machine learning para processar e interpretar texto e dados. O reconhecimento de linguagem natural e a geração de linguagem natural são tipos de PLN. Portanto, é importante que todos no grupo tenham conhecimento sobre o assunto para a realização do projeto. Além disso existem diversos modelos para machine learning e muitos deles podem ser encontrados na **scikit-learn**, que é uma biblioteca de aprendizado de máquina de código aberto para a linguagem de programação Python.

## Tarefas
- [x] Estudar sobre machine learning e PLN: [Natural Language Processing (NLP) & Text Mining Tutorial | Machine Learning Tutorial | Simplilearn](https://www.youtube.com/watch?v=7WfoYl-EPtI)
- [x] Estudar a biblioteca scikit-learn: [scikit-learn: Machine Learning in Python](https://scikit-learn.org/stable/)
- [x] Montar algum projeto rápido de machine learning e upar notebook em: [2022-2-Squad03](https://github.com/fga-eps-mds/2022-2-Squad03/tree/feature-1)/[Estudos](https://github.com/fga-eps-mds/2022-2-Squad03/tree/feature-1/Estudos)/Introduçao a Machine Learning/

## Critério de aceitação
- [ ] commit do projeto

**Comment by G16C** [comment]
https://www.youtube.com/watch?v=o8NpsLSkKUo

Achei esse vídeo que dá um norte de como começar a estudar ciência de dados.

**Comment by dougAlvs** [comment]
Já que todos estudaram o conteúdo proposto e enviaram os estudos de Machine Leaning, os critérios de aceitação da issue foram completados
