### ISSUE TITLE
inserir release note

### ISSUE THREAD

**Issue by nando3d3** [fga-eps-mds/2022-2-IsItKbs#91]
## Descrição
Uma release note é um relatório publicado juntamente com software novo ou atualizado que detalha os recursos técnicos do produto. Para novos lançamentos, essas notas fornecem aos usuários finais um breve resumo do próprio produto.

### Descrição
- [x] Resumo do que foi feito na primeira fase
- [x] Lista das funcionalidades entregues (com a issue relacionada)
- [x] Lista de artefatos realizados (docs feitos)
### Bugs
- [x] O que foi encontrado de problemas e precisam resolver na r2

## Critério de aceitação

- [x] Apresentar os tópicos descritos acima

**Comment by arthurgrandao** [comment]
Eu e Rafael, escrevemos e publicamos a release notes da nossa Release 1.

**Comment by G16C** [comment]
Revisei e está de acordo com os critérios, fecharei a issue
