### ISSUE TITLE
melhorar README

### ISSUE THREAD

**Issue by nando3d3** [fga-eps-mds/2022-2-IsItKbs#92]
## Descrição

Há pontos que devem ser implementados em nosso readme
## Tarefas

- [x] Badges (Opcional)
- [x] #95
- [x] Tabela de conteúdos
- [x] Features
- [x] Demonstração
- [x] Pré-requisito e como rodar
- [x] Tecnologias utilizadas

## Critério de aceitação

- [x] Os tópicos descritos acima estão aceitáveis

**Comment by G16C** [comment]
Já colocaram o status do projeto?
