### ISSUE TITLE
Estudar GitHub Actions

### ISSUE THREAD

**Issue by arthurgrandao** [fga-eps-mds/2022-2-IsItKbs#98]
## Descrição
Estudar GitHub Actions para podermos progredir na parte organizacional do projeto.

## Tarefas

- [x] Estudar GitHub Actions;

## Critério de aceitação

- [x] Compreender como funcionam as GitHub Actions;

**Comment by G16C** [comment]
Já apliquei a automação de testes unitários na minha branch. Agora só falta criar um pull request e dar merge com a main.

**Comment by G16C** [comment]
Terminei
