### ISSUE TITLE
Resolver a Expiração do Zenhub

### ISSUE THREAD

**Issue by arthurmlv** [fga-eps-mds/2022-2-IsItKbs#99]
## Descrição

Dado que o Zenhub expira após um determinado tempo, necessita-se do preenchimento de um formulário para a reativação do Zenhub.
## Tarefas

- [ ] Preenchimento e envio do formulário.

## Critério de aceitação

- [ ] Zenhub voltar a funcionar.

**Comment by PauloVictorFS** [comment]
foi enviado um formulario de ativação do zenhub solicitando acesso , porém apenas forneceram acesso a mim , e não ao resto do grupo

**Comment by PauloVictorFS** [comment]
o resto do grupo enviou o formulario , e estamos esperando a resposta do zenhub

**Comment by dougAlvs** [comment]
Visto que mesmo após comunicação com o Zenhub as licenças não foram liberadas para todos no grupo, estaremos fechando essa issue.
